### ISSUE TITLE
ModelMesh crash loops after running install script following quick start guide

### ISSUE THREAD

**Issue by OvervCW** [kserve/modelmesh-serving#183]
**Describe the bug**

The ModelMesh pod crash loops after installing it using the `install.sh` script, see the steps to reproduce.

**To Reproduce**

1. Follow the instructions in https://github.com/kserve/modelmesh-serving/blob/main/docs/quickstart.md
2. After running `./scripts/install.sh --namespace modelmesh-serving --quickstart`, observe that the `modelmesh-controller-xxx` pod enters a crash loop:

```
NAME                                    READY   STATUS             RESTARTS      AGE
etcd                                    1/1     Running            0             8m50s
minio                                   1/1     Running            0             8m50s
modelmesh-controller-5fc454979f-l5g7w   0/1     CrashLoopBackOff   3 (23s ago)   2m26s
```

The cause of the crash appears to be a Go panic:

```
...
"level":"info","ts":1657287819.5079787,"logger":"controller.ServiceReconciler","msg":"Starting EventSource","reconciler group":"","reconciler kind":"Namespace","source":"kind source: /, Kind="}
{"level":"info","ts":1657287819.507999,"logger":"controller.ServiceReconciler","msg":"Starting Controller","reconciler group":"","reconciler kind":"Namespace"}
{"level":"info","ts":1657287819.5081367,"logger":"controller.predictor","msg":"Starting EventSource","reconciler group":"serving.kserve.io","reconciler kind":"Predictor","source":"kind source: /, Kind="}
{"level":"info","ts":1657287819.508163,"logger":"controller.predictor","msg":"Starting EventSource","reconciler group":"serving.kserve.io","reconciler kind":"Predictor","source":"channel source: 0xc000185a40"}
{"level":"info","ts":1657287819.5081854,"logger":"controller.predictor","msg":"Starting EventSource","reconciler group":"serving.kserve.io","reconciler kind":"Predictor","source":"kind source: /, Kind="}
{"level":"info","ts":1657287819.5081944,"logger":"controller.predictor","msg":"Starting Controller","reconciler group":"serving.kserve.io","reconciler kind":"Predictor"}
{"level":"info","ts":1657287819.6085188,"logger":"controller.endpoints","msg":"Starting workers","reconciler group":"","reconciler kind":"Endpoints","worker count":1}
{"level":"info","ts":1657287819.6102252,"logger":"controller.ServingRuntimeReconciler","msg":"Starting workers","reconciler group":"serving.kserve.io","reconciler kind":"ServingRuntime","worker count":1}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x1505c1d]

goroutine 535 [running]:
github.com/kserve/modelmesh-serving/controllers.(*ServingRuntimeReconciler).Reconcile(0xc00037e900, {0x1aaff18, 0xc0006ac7b0}, {{{0xc0006d8dea, 0x6}, {0xc0006d8d60, 0xc}}})
        /workspace/controllers/servingruntime_controller.go:120 +0x37d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0002d5f40, {0x1aaff18, 0xc0006ac6c0}, {{{0xc0006d8dea, 0x17474c0}, {0xc0006d8d60, 0xc0005e3900}}})
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:114 +0x222
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002d5f40, {0x1aafe70, 0xc0005e2040}, {0x16cd7e0, 0xc00072a560})
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:311 +0x2f2
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002d5f40, {0x1aafe70, 0xc0005e2040})
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:223 +0x354
```

**Expected behavior**

A running modelmesh controller pod.

**Screenshots**

N/A

**Environment (please complete the following information):**

- OS: Ubuntu 22.04 LTS
- `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"5a97ee6d15525f6e4a1c2646bf1dfd2ebd5220b5", GitTreeState:"clean", BuildDate:"2022-06-15T04:26:33Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```
- `kustomize version`
```
{Version:kustomize/v4.5.5 GitCommit:daa3e5e2c2d3a4b8c94021a7384bfb06734bcd26 BuildDate:2022-05-20T20:25:40Z GoOs:linux GoArch:amd64}
```
- modelmesh-serving version: `release-0.8`

**Comment by OvervCW** [comment]
Nevermind, I fixed the problem by removing the modelmesh-controller in a different namespace (`kserve`) that had been installed by the `kserve` Helm chart. Apparently they were conflicting with each other somehow.
