### ISSUE TITLE
Fail to build Docker develop image.

### ISSUE THREAD

**Issue by Jooho** [kserve/modelmesh-serving#477]
**Describe the bug**
when the build start with `make build`, it failed with the following message.
~~~
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 565, in untar_file
    tarfile.data_filter(member.replace(name=fn), location)
AttributeError: module 'tarfile' has no attribute 'data_filter'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 346, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 381, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 623, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3.6/site-packages/pip/download.py", line 822, in unpack_url
    hashes=hashes
  File "/usr/lib/python3.6/site-packages/pip/download.py", line 664, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 622, in unpack_file
    untar_file(filename, location)
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 566, in untar_file
    except tarfile.LinkOutsideDestinationError:
AttributeError: module 'tarfile' has no attribute 'LinkOutsideDestinationError'
~~~
**To Reproduce**

`make docker-build`

**Expected behavior**
It successfully builds the develop image.

**Screenshots**

**Environment (please complete the following information):**

- OS: Fedora

**Additional context**

**Comment by Jooho** [comment]
closed because it does not reproduce anymore.
